// DO NOT EDIT. generated by github.com/tinywasm/orm

package contact

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/form/input"
)

var _schemaContactForm = []fmt.Field{
		{Name: "nombre", Type: fmt.FieldText, NotNull: true, Widget: input.Text(), Permitted: fmt.Permitted{Minimum: 2}},
		{Name: "email", Type: fmt.FieldText, NotNull: true, Widget: input.Email()},
		{Name: "mensaje", Type: fmt.FieldText, NotNull: true, Widget: input.Textarea(), Permitted: fmt.Permitted{Minimum: 10}},
	}

func (m *ContactForm) Schema() []fmt.Field { return _schemaContactForm }

func (m *ContactForm) Pointers() []any {
	return []any{
		&m.Nombre,
		&m.Email,
		&m.Mensaje,
	}
}

func (m *ContactForm) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

